version: "3.8" # Версия синтаксиса Docker Compose

services:
  db: # Название нашего сервиса базы данных
    image: postgres:16-alpine # Используем официальный образ PostgreSQL версии 16 (alpine - легковесный)
    restart: always # Всегда перезапускать контейнер, если он упал
    environment: # Переменные окружения для PostgreSQL
      POSTGRES_DB: micro_chirp_db # Имя базы данных, которую мы хотим создать
      POSTGRES_USER: dima # Имя пользователя для подключения к БД
      POSTGRES_PASSWORD: 2025 # Пароль для пользователя для подключения к БД
    ports:
      - "5432:5432" # Пробрасываем порт 5432 контейнера на порт 5432 вашей хост-машины
    volumes:
      - db_data:/var/lib/postgresql/data # Сохраняем данные БД в именованный том, чтобы они не терялись при перезапуске/удалении контейнера

volumes:
  db_data: # Объявляем именованный том
